#!/bin/bash

#Evan Widloski - 2013 
#i3wm status line output example written in bash
 
echo '{ "version": 1 }'
echo '['
echo '[]'
 
while :
do
	datesec=$(date +%s)
    ###Send out to status bar
    #Put a comma at the end of each string EXCEPT the last one
	echo -n ",["

	#Make as many of these lines as you want
    echo -n "{\"name\":\"time\",\"color\":\"#4284D3\",\"full_text\":\"$datesec\"}," 
    echo -n "{\"name\":\"time\",\"color\":\"#4284D3\",\"full_text\":\"$datesec\"}," 
    echo -n "{\"name\":\"time\",\"color\":\"#4284D3\",\"full_text\":\"$datesec\"}" 


    echo -n "]"
 
    sleep 1
 
done
