#!/bin/bash

#Evan Widloski - 2013 
#A simplified statusline script for i3 demonstrating how to use the protocol
 
echo '{ "version": 1 }'
echo '['
echo '[]'
 
while :
do
	current_time=$(date +%H:%M)
	field2="Field2"
	field3="Field3"

	#Send out to status bar
	echo -n ",["
	#Add as many custom fields as you want
	echo -n "{\"name\":\"time\",\"color\":\"#4284D3\",\"full_text\":\"$current_time\"}," 
	echo -n "{\"name\":\"field1\",\"color\":\"#ffff00\",\"full_text\":\"$field2\"}," 
	echo -n "{\"name\":\"field2\",\"color\":\"#ff9200\",\"full_text\":\"$field3\"}" 

	#(note: the last echo statement does not have a trailing comma)

    echo -n "]"
    sleep 1
done
